name: portefeuille
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.2
  fl_chart: ^1.1.1
  cupertino_icons: ^1.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.20.2
  uuid: ^4.4.0
  shimmer: ^3.0.0
  animated_text_kit: ^4.2.2
  http: ^1.2.1
  flutter_secure_storage: ^9.1.1
  file_picker: ^8.0.0
  share_plus: ^9.0.0
  path_provider: ^2.1.3
  google_fonts: ^6.1.0
  flutter_typeahead: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Dépendances pour la génération de code Hive
  hive_generator: ^2.0.1
  build_runner: ^2.4.9

  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  windows:
    generate: true
  # Spécifiez le chemin vers votre image source
  image_path: "assets/icon/icon.png"