name: portefeuille
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.2
  fl_chart: ^1.1.1
  cupertino_icons: ^1.0.8

  # Dépendances pour le stockage local
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Dépendance pour le formatage
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Dépendances pour la génération de code Hive
  hive_generator: ^2.0.1
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
